#!/usr/bin/env ruby

require 'optparse'
require 'artii'

require 'bundler/setup'
require 'xkpassword'

artii = Artii::Base.new font: 'standard'
message = """
#{ artii.asciify('XKPassword') }
by Ziyan Junaideen

How many times have you changed your password just because you forgot it?
Well, you are not alone. In todays security requirements, passwords need
to be secure and difficult to break. Passwords need to be secure, sure,
but they can also be easy to remember. Follow up this XKCD article for more
information - http://xkcd.com/936/

This does exactly what the picture predicts. You can use this in your Ruby 
applications (Ex: Rails, Sinatra) or standalone if you install the gem (as 
you have done here).

Wish you all the best keeping things secure.

Ziyan Junaideen
ziyan@jdeen.com

"""

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: ./exe/xkpassword [options]"

  opts.on('-v', '--version', 'Gem version') { options[:version] = true }
  opts.on('-i', '--info', 'Gem info') { options[:info] = true }

  opts.on('--words [INTEGER]', 'Number of wrods to be used in the generated password') { |words| options[:words] = words.to_i }
  opts.on('--min-length [INTEGER]', 'Minimum length of a word') { |min| options[:min_length] = min.to_i }
  opts.on('--max-length [INTEGER]', 'Maximum length of a word') { |max| options[:max_length] = max.to_i }
  opts.on('--separator [STRING]', 'The separator to separate password') { |separator| options[:separator] = separator }
end.parse!

puts message if options[:info]
puts XKPassword::VERSION if options[:version]
puts XKPassword.generate(options) if !options[:info] && !options[:version]


